(()=>{var e=globalThis,t={},r={},a=e.parcelRequire4cfd;null==a&&((a=function(e){if(e in t)return t[e].exports;if(e in r){var a=r[e];delete r[e];var s={id:e,exports:{}};return t[e]=s,a.call(s.exports,s,s.exports),s.exports}var i=Error("Cannot find module '"+e+"'");throw i.code="MODULE_NOT_FOUND",i}).register=function(e,t){r[e]=t},e.parcelRequire4cfd=a),(0,a.register)("cg86O",function(e,t){Object.defineProperty(e.exports,"DEFAULT_ORIGIN_LIST",{get:()=>r,set:void 0,enumerable:!0,configurable:!0});let r=["https://hoppscotch.io"]});var s=a("cg86O");let i=new AbortController,n=e=>Object.entries(e).reduce((t,[r,a])=>"content-type"==r&&"multipart/form-data"==e[r]?{...t}:{...t,[r]:a.toString()},{});async function o(e){let t=n(e.headers),r={timeData:{}};r.timeData.startTime=new Date().getTime();let a=e.params;if(a)try{let t=new URLSearchParams(e.url.split("?")[1]);Object.keys(a).forEach(e=>{t.append(e,a[e])}),e.url=e.url.split("?")[0]+`?${t.toString()}`}catch(e){}// TODO: check different examples with axios body
let s=await fetch(e.url,{headers:{...t},method:e.method,// Ignore the body for GET and HEAD requests to prevent error with axios
body:["get","head"].includes(e.method?.toLowerCase())?void 0:e.data,signal:i.signal});return r.timeData.endTime=new Date().getTime(),[s,r]}let l=e=>{let t=e.split(","),r=t[0].match(/:(.*?);/)[1],a=atob(t[1]),s=a.length,i=new Uint8Array(s);for(;s--;)i[s]=a.charCodeAt(s);let n=new Blob([i],{type:r});return n},c=e=>e.split(";").map(e=>e.split("=")).reduce((e,t)=>(t[0]&&t[1]&&(e[decodeURIComponent(t[0].trim())]=decodeURIComponent(t[1].trim())),e),{}),d={},u=async()=>{if(d.url&&d.cookies){for(let e of d.cookies)await chrome.cookies.remove({url:d.url,name:e});d={}}},m=async e=>{let t=Object.entries(e.headers||{}).find(([e])=>"cookie"===e.toLowerCase());if(t&&e.url&&"string"==typeof t[1]){d={url:e.url,cookies:[]};let r=c(t[1]);for(let[t,a]of Object.entries(r))await chrome.cookies.set({url:e.url,name:t,value:a}),d.cookies.push(t)}return e},p=e=>{if(e.formData||e.formFiles){let t=new FormData;e.formFiles.forEach(({key:e,value:r,filename:a})=>{t.append(e,l(r),a)}),e.formData.forEach(({key:e,value:r})=>{t.append(e,r)}),e.data=t,e.formFiles=null,e.formData=null}return e},f=async e=>(await m(e),p(e));function g(e){return btoa(new Uint8Array(e).reduce((e,t)=>e+String.fromCharCode(t),""))}let h=async(e,t)=>{if(t&&(t.startsWith("application/json")||t.startsWith("application/vnd.api+json")||t.startsWith("application/hal+json")))try{e=JSON.parse(e)}catch(e){}},y=e=>{let t={};return e.forEach((e,r)=>{t[r]=e}),t},N=async e=>{try{let t=await f(e);if(e.wantsBinary){let[e,r]=await o({...t,responseType:"arraybuffer",validateStatus:()=>!0}),a=y(e.headers);return{messageType:"recv-req",data:{response:{status:e.status,statusText:e.statusText,headers:a,responseURL:e.url,data:g(await e.arrayBuffer()),timeData:r.timeData},isBinary:!0,error:null}}}{let[e,r]=await o({...t}),a=await e.text(),s=e.headers.get("content-type"),i=await h(a,s),n=y(e.headers);return{messageType:"recv-req",data:{response:{status:e.status,statusText:e.statusText,headers:n,responseURL:e.url,data:i,timeData:r.timeData},isBinary:!1,error:null}}}}catch(e){return{messageType:"recv-req",data:{response:null,error:function(e){if(e.response&&e.response.data)try{e.response.data=g(e.response.data)}catch(e){}// This mess below is a hack to go around Firefox's memory bounding system
return{// Standard
message:e.message?JSON.parse(JSON.stringify(e.message)):void 0,name:e.name?JSON.parse(JSON.stringify(e.name)):void 0,// Mozilla
fileName:e.fileName?JSON.parse(JSON.stringify(e.fileName)):void 0,lineNumber:e.lineNumber?JSON.parse(JSON.stringify(e.lineNumber)):void 0,columnNumber:e.columnNumber?JSON.parse(JSON.stringify(e.columnNumber)):void 0,stack:e.stack?JSON.parse(JSON.stringify(e.stack)):void 0,// Axios
response:e.response?JSON.parse(JSON.stringify(e.response)):void 0}}(e)}}}finally{// remove the cookies set for this request
await u()}},O=()=>{i.abort(),// reset the abort controller for the next request
i=new AbortController};chrome.runtime.onMessage.addListener((e,t,r)=>"send-req"===e.messageType?(N(e.data).then(r),!0):"cancel-req"===e.messageType?(O(),!0):void 0),chrome.storage.sync.get(e=>{JSON.parse(e.originList)}),chrome.storage.onChanged.addListener((e,t)=>{e.originList&&e.originList.newValue&&JSON.parse(e.originList.newValue)}),chrome.tabs.onUpdated.addListener((e,t,r)=>{"loading"!==r.status&&chrome.tabs.sendMessage(r.id,{action:"__POSTWOMAN_EXTENSION_PING__"},e=>{chrome.runtime.lastError?chrome.scripting.executeScript({target:{tabId:r.id},files:["contentScript.js"]}):console.log("Already hooked")})}),chrome.runtime.onInstalled.addListener(()=>{chrome.storage.sync.get(e=>{e.originList||chrome.storage.sync.set({originList:JSON.stringify(s.DEFAULT_ORIGIN_LIST)},()=>{})})}),chrome.runtime.onMessage.addListener((e,t)=>{if(e.type&&"execute_hook"==e.type&&t.tab.id){let r="VALID_ORIGIN"==e.origin_type?["hookContent.js"]:["hookContentInvalidOrigin.js"];chrome.scripting.executeScript({target:{tabId:t.tab.id},files:r,world:"MAIN"})}})})();//# sourceMappingURL=index.js.map

//# sourceMappingURL=index.js.map
