local Plug = vim.fn["plug#"]

vim.call("plug#begin", "~/.config/nvim/plugged")

Plug("mfussenegger/nvim-jdtls")
Plug("petertriho/nvim-scrollbar")
Plug("Shatur/neovim-ayu")
Plug("nvim-telescope/telescope.nvim")
Plug("nvim-telescope/telescope-file-browser.nvim")
Plug("sbdchd/neoformat")
Plug("m4xshen/autoclose.nvim")
Plug("windwp/nvim-ts-autotag")
Plug("akinsho/bufferline.nvim")
Plug("lewis6991/gitsigns.nvim")
Plug("nvim-treesitter/nvim-treesitter", { ["do"] = ":TSUpdate" })
Plug("numToStr/Comment.nvim")
Plug("kyazdani42/nvim-web-devicons")
Plug("nvim-lualine/lualine.nvim")
Plug("nvim-lua/plenary.nvim")
Plug("onsails/lspkind.nvim")
Plug("lukas-reineke/indent-blankline.nvim")
Plug("glepnir/dashboard-nvim")
Plug("neovim/nvim-lspconfig")
Plug("williamboman/mason-lspconfig.nvim")
Plug("hrsh7th/nvim-cmp")
Plug("hrsh7th/cmp-nvim-lsp")
Plug("L3MON4D3/LuaSnip")
Plug("saadparwaiz1/cmp_luasnip")
Plug("rafamadriz/friendly-snippets")
Plug("williamboman/mason.nvim")
Plug("VonHeikemen/lsp-zero.nvim", { ["branch"] = "v2.x" })

vim.call("plug#end")
